### ISSUE TITLE
Add a language icon or logo

### ISSUE THREAD

**Issue by yurrriq** [exercism/xidris#6]
See #1

**Comment by srenatus** [comment]
Seems like the repo [has an icon.png](https://github.com/exercism/xidris/commit/a2858ab43bc6a32269f5b97e43b11f9fcfe7584e). Is that sufficient? [There are SVGs available, too, here](https://github.com/idris-lang/Idris-dev/tree/3b95b07b14973417b5016cb4cb496d22c7e23578/logos), but I'm not sure how they'd be used (e.g., does it need a certain format? os is png good enough?)

**Comment by yurrriq** [comment]
It shows up on http://exercism.io/languages so it seems good enough to me. Closing until proven wrong. Thanks.
